---
- name: "Deploy '{{ ansible_pkg_mgr }}' based configuration"
  template:
    src:   "{{ ansible_pkg_mgr }}/{{ item.name }}.j2"
    dest:  "{{ item.path }}/{{ item.name }}"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "{{ conf.files }}"
  tags:
  - conf

- name: "Create daemon serve directory"
  file:
    dest:  "{{ item }}"
    state: directory
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rwx,g=rx,o=rx"
  with_items:
  - "{{ conf.root_dir }}"
  tags:
  - conf

