# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Nylox. <https://github.com/nylox/nylox.git>
#
#    Nylox is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nylox is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nylox.  If not, see <http://www.gnu.org/licenses/>.
#

---
pacman:
  packages:  []
  services:  []
  username:  ""
  groupname: ""
  root_dir:  ""
  conf_file: ""
  conf_dir:  ""

apt:
  packages:  []
  services:  []
  username:  ""
  groupname: ""
  root_dir:  ""
  conf_file: ""
  conf_dir:  ""

yum:
  packages:  []
  services:  []
  username:  ""
  groupname: ""
  root_dir:  ""
  conf_file: ""
  conf_dir:  ""

conf: "{}"

#bind_host: "127.0.0.1"
#bind_port: "12345"

sshauth_remote_user: "toor"
sshauth_remote_pass: "toor:123"

sshauth_exclusive_key: yes

service_final:
  state: "restarted"
  enabled: "yes"

